# Generated by Django 4.1.5 on 2023-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_people_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tech/static/img'),
        ),
    ]
