# Generated by Django 4.1.7 on 2023-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_alter_people_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
