# Generated by Django 4.1.7 on 2023-03-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_people_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
