# Generated by Django 4.1.5 on 2023-03-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_sign_in_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign',
            new_name='sign_in',
        ),
    ]
